### ISSUE TITLE
Issue with GraphMachine

### ISSUE THREAD

**Issue by paolodina** [PrimarySite/django-transitions#7]
I've been able to follow the docs and have the example working. I tried to swap the `machine` instance from `Machine` to `GraphMachine` and still can save the new instance using Django admin to assign the initial state, but got an exception clicking on the transition button (I tried using the Django shell and the transitions methods are present but give the same issue).

If I'm not doing something wrong, are graph machines supported? I also plan to use hierarchical machines and wonder if there could be any problem.

```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/admin/backend/machinecli/2/change/

Django Version: 3.2.7
Python Version: 3.8.10
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'backend')
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/user/devel/.venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/user/devel/.venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/devel/.venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/user/devel/.venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/user/devel/.venv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/user/devel/.venv/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/user/devel/.venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1660, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/user/devel/.venv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/user/devel/.venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/user/devel/.venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/user/devel/.venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1594, in _changeform_view
    return self.response_change(request, new_object)
  File "/home/user/devel/.venv/lib/python3.8/site-packages/django_transitions/admin.py", line 25, in response_change
    if getattr(obj, event['transition'].name)():
  File "/home/user/devel/.venv/lib/python3.8/site-packages/transitions/core.py", line 401, in trigger
    return self.machine._process(func)
  File "/home/user/devel/.venv/lib/python3.8/site-packages/transitions/core.py", line 1187, in _process
    return trigger()
  File "/home/user/devel/.venv/lib/python3.8/site-packages/transitions/core.py", line 426, in _trigger
    return self._process(event_data)
  File "/home/user/devel/.venv/lib/python3.8/site-packages/transitions/core.py", line 435, in _process
    if trans.execute(event_data):
  File "/home/user/devel/.venv/lib/python3.8/site-packages/transitions/core.py", line 276, in execute
    self._change_state(event_data)
  File "/home/user/devel/.venv/lib/python3.8/site-packages/transitions/extensions/diagrams.py", line 30, in _change_state
    graph = event_data.machine.model_graphs[id(event_data.model)]

Exception Type: KeyError at /admin/backend/machinecli/2/change/
Exception Value: 140334884199680
```

**Comment by paolodina** [comment]
I saw this implementation just now. https://github.com/PrimarySite/django-transitions/blob/master/django_transitions/workflow.py
